/* ============================================================
   app.js
   App boot + event delegation. Most controls use data-* attrs,
   keeping the HTML generated by pillar views straightforward.
   ============================================================ */
(function () {
  const Store = window.PremedStore;
  const UI = window.PremedUI;
  const Pillars = window.PremedPillars;

  let state = Store.load();
  let dragPayload = null;
  let pomoInterval = null;

  const nav = document.getElementById('nav');
  const main = document.getElementById('main');
  const sidebar = document.getElementById('sidebar');
  const backupStatus = document.getElementById('backupStatus');

  buildNav();
  render();

  Store.subscribe((next) => {
    state = next;
    buildNav();
    render();
  });

  document.getElementById('navToggle')?.addEventListener('click', () => sidebar.classList.toggle('open'));
  document.getElementById('quickAddBtn')?.addEventListener('click', openQuickAdd);

  document.body.addEventListener('click', handleClick);
  document.body.addEventListener('change', handleChange);
  document.body.addEventListener('input', handleInput);
  document.body.addEventListener('submit', handleSubmit);
  document.body.addEventListener('dragstart', handleDragStart);
  document.body.addEventListener('dragover', handleDragOver);
  document.body.addEventListener('dragleave', handleDragLeave);
  document.body.addEventListener('drop', handleDrop);

  function buildNav() {
    const grouped = {};
    Pillars.routes.forEach((r) => (grouped[r.group] ||= []).push(r));
    const active = state?._ui?.route || 'home';
    nav.innerHTML = Object.entries(grouped).map(([group, routes]) => `
      <div class="nav-group">
        <div class="nav-group-label">${UI.esc(group)}</div>
        ${routes.map((r) => `<button class="nav-item ${active === r.id ? 'active' : ''}" data-route="${r.id}">
          <span class="ni-icon">${UI.esc(r.icon)}</span>
          <span>${UI.esc(r.label)}</span>
        </button>`).join('')}
      </div>
    `).join('');
  }

  function render() {
    const route = state._ui.route || 'home';
    main.innerHTML = Pillars.render(route, state);
    backupStatus.textContent = backupText(state);
    backupStatus.classList.toggle('ok', !!state._meta.lastBackupAt && !state._meta.lastBackupError);
    UI.runCharts();
    syncPomodoroDisplay();
  }

  function backupText(s) {
    if (s._meta.lastBackupError) return `Backup needs attention: ${s._meta.lastBackupError}`;
    if (s._meta.lastBackupAt) return `Last Drive backup ${UI.relativeTime(s._meta.lastBackupAt)}`;
    if (s._meta.drive?.clientId) return 'Drive configured; connect to back up';
    return 'Local autosave on; Drive optional';
  }

  async function handleClick(event) {
    const close = event.target.closest('[data-close]');
    if (close) {
      UI.closeModal();
      return;
    }

    const route = event.target.closest('[data-route]');
    if (route) {
      Store.setRoute(route.dataset.route);
      sidebar.classList.remove('open');
      return;
    }

    const actionEl = event.target.closest('[data-action]');
    if (!actionEl) return;
    const action = actionEl.dataset.action;

    if (action === 'add-row') {
      const template = JSON.parse(actionEl.dataset.template || '{}');
      const item = hydrateTemplate(template);
      Store.addItem(actionEl.dataset.path, item, `Added ${labelFromPath(actionEl.dataset.path)}`);
      return;
    }
    if (action === 'delete-row') {
      Store.removeItem(actionEl.dataset.path, actionEl.dataset.index, `Deleted ${labelFromPath(actionEl.dataset.path)}`);
      return;
    }
    if (action === 'move-row') {
      Store.moveItem(actionEl.dataset.path, actionEl.dataset.index, actionEl.dataset.dir, `Reordered ${labelFromPath(actionEl.dataset.path)}`);
      return;
    }
    if (action === 'set-ui') {
      Store.set(`_ui.${actionEl.dataset.key}`, actionEl.dataset.value);
      return;
    }
    if (action === 'calendar-shift') {
      shiftCalendar(Number(actionEl.dataset.dir || 0));
      return;
    }
    if (action === 'add-focus') {
      Store.addItem('focusTargets', { id: Store.uid('f'), text: 'New focus target', done: false }, 'Added focus target');
      return;
    }
    if (action === 'export-json') {
      Store.exportJson();
      UI.toast('Exported JSON backup.');
      return;
    }
    if (action === 'reset-seed') {
      if (confirm('Reset this browser copy back to the seed data? Export first if you want to keep current data.')) {
        Store.resetToSeed();
      }
      return;
    }
    if (action === 'connect-drive') {
      try {
        await Store.backup.connectDrive();
      } catch (err) {
        UI.toast(err.message || String(err));
      }
      return;
    }
    if (action === 'backup-drive') {
      try {
        await Store.backup.backupNow({ interactive: true, reason: 'manual' });
        UI.toast('Backed up to Google Drive.');
      } catch (err) {
        UI.toast(err.message || String(err));
      }
      return;
    }
    if (action === 'delete-kanban') {
      Store.update((s) => {
        s.kanban[actionEl.dataset.status].splice(Number(actionEl.dataset.index), 1);
      }, 'Deleted sprint card');
      return;
    }
    if (action === 'pomo-start') {
      startPomodoro();
      return;
    }
    if (action === 'pomo-pause') {
      pausePomodoro();
      return;
    }
    if (action === 'pomo-reset') {
      resetPomodoro();
      return;
    }
    if (action === 'add-kanban') {
      const title = prompt('Sprint card title');
      if (title) {
        Store.update((s) => {
          s.kanban[actionEl.dataset.status].push({ id: Store.uid('kan'), title, note: '' });
        }, 'Added sprint card');
      }
      return;
    }
  }

  function handleInput(event) {
    const el = event.target.closest('[data-edit-path]');
    if (!el) return;
    // Text-like inputs save immediately without a full re-render, so typing stays smooth.
    if (el.matches('input[type="text"], input[type="url"], input[type="number"], input:not([type]), textarea')) {
      Store.setQuiet(el.dataset.editPath, inputValue(el));
    }
  }

  async function handleChange(event) {
    const importInput = event.target.closest('input[data-action="import-json"]');
    if (importInput?.files?.[0]) {
      try {
        await Store.importJson(importInput.files[0]);
        UI.toast('Imported JSON backup.');
      } catch (err) {
        UI.toast('Import failed: ' + (err.message || String(err)));
      } finally {
        importInput.value = '';
      }
      return;
    }

    const el = event.target.closest('[data-edit-path]');
    if (!el) return;
    Store.set(el.dataset.editPath, inputValue(el), `Updated ${labelFromPath(el.dataset.editPath)}`);
  }

  function handleSubmit(event) {
    const form = event.target.closest('[data-quick-add-form]');
    if (!form) return;
    event.preventDefault();
    const data = new FormData(form);
    const type = data.get('type');
    const title = String(data.get('title') || '').trim();
    const notes = String(data.get('notes') || '').trim();
    if (!title) return;
    if (type === 'task') {
      Store.addItem('tasks', { id: Store.uid('t'), name: title, due: String(data.get('date') || ''), status: 'To-Do', cat: 'Quick Add', notes }, 'Quick-added task');
    } else if (type === 'story') {
      Store.addItem('stories', { id: Store.uid('s'), title, date: String(data.get('date') || UI.todayIso()), tags: '', body: notes, commentary: '', status: 'Open' }, 'Quick-added story');
    } else if (type === 'clinical') {
      Store.addItem('clinical', { id: Store.uid('clin'), site: title, role: '', date: String(data.get('date') || UI.todayIso()), hours: Number(data.get('hours')) || '', contact: '', description: notes, reflection: '', fileUrl: '', status: 'Planned' }, 'Quick-added clinical entry');
    }
    UI.closeModal();
  }

  function handleDragStart(event) {
    const card = event.target.closest('.kan-card');
    if (!card) return;
    dragPayload = { from: card.dataset.kanbanStatus, index: Number(card.dataset.kanbanIndex) };
    event.dataTransfer.effectAllowed = 'move';
    event.dataTransfer.setData('text/plain', JSON.stringify(dragPayload));
  }

  function handleDragOver(event) {
    const col = event.target.closest('[data-kanban-col]');
    if (!col || !dragPayload) return;
    event.preventDefault();
    col.classList.add('drop-hover');
  }

  function handleDragLeave(event) {
    const col = event.target.closest('[data-kanban-col]');
    if (col) col.classList.remove('drop-hover');
  }

  function handleDrop(event) {
    const col = event.target.closest('[data-kanban-col]');
    if (!col || !dragPayload) return;
    event.preventDefault();
    col.classList.remove('drop-hover');
    const to = col.dataset.kanbanCol;
    Store.update((s) => {
      const fromArr = s.kanban[dragPayload.from] || [];
      const [card] = fromArr.splice(dragPayload.index, 1);
      if (card) (s.kanban[to] ||= []).push(card);
    }, 'Moved sprint card');
    dragPayload = null;
  }

  function hydrateTemplate(template) {
    const item = { ...template };
    if (!item.id) item.id = Store.uid('row');
    Object.keys(item).forEach((key) => {
      if (item[key] === '__today__') item[key] = UI.todayIso();
    });
    return item;
  }

  function inputValue(el) {
    if (el.type === 'checkbox') return el.checked;
    if (el.type === 'number') return el.value === '' ? '' : Number(el.value);
    return el.value;
  }

  function shiftCalendar(dir) {
    const current = state._ui.calendarMonth || UI.todayIso().slice(0, 7);
    const [y, m] = current.split('-').map(Number);
    const d = new Date(y, m - 1 + dir, 1);
    const next = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
    Store.set('_ui.calendarMonth', next);
  }

  function openQuickAdd() {
    UI.openModal(`
      <form data-quick-add-form>
        <h3>Quick add</h3>
        <div class="form-row">
          <label>Type</label>
          <select name="type">
            <option value="task">Task</option>
            <option value="story">Story bank note</option>
            <option value="clinical">Clinical hour entry</option>
          </select>
        </div>
        <div class="form-row"><label>Title / site</label><input name="title" required></div>
        <div class="form-row"><label>Date / due date</label><input name="date" type="date"></div>
        <div class="form-row"><label>Hours (optional)</label><input name="hours" type="number" step="0.25"></div>
        <div class="form-row"><label>Notes</label><textarea name="notes" rows="4"></textarea></div>
        <div class="modal-actions">
          <button class="btn" type="button" data-close="1">Cancel</button>
          <button class="btn btn-primary" type="submit">Add</button>
        </div>
      </form>
    `);
  }

  function labelFromPath(path) {
    const clean = String(path || '').split('.').filter((p) => Number.isNaN(Number(p))).pop() || 'item';
    return clean.replace(/([A-Z])/g, ' $1').toLowerCase();
  }

  function pomoSecs() {
    const mins = Number(state.study?.pomodoroMinutes) || 25;
    if (state._ui.pomodoroSecs != null) return state._ui.pomodoroSecs;
    return mins * 60;
  }

  function syncPomodoroDisplay() {
    const node = document.getElementById('pomoDisplay');
    if (!node) return;
    const secs = pomoSecs();
    node.textContent = `${String(Math.floor(secs / 60)).padStart(2, '0')}:${String(secs % 60).padStart(2, '0')}`;
  }

  function startPomodoro() {
    if (pomoInterval) return;
    Store.setQuiet('_ui.pomodoroRunning', true);
    if (state._ui.pomodoroSecs == null) {
      Store.setQuiet('_ui.pomodoroSecs', (Number(state.study?.pomodoroMinutes) || 25) * 60);
    }
    pomoInterval = setInterval(() => {
      const next = pomoSecs() - 1;
      if (next <= 0) {
        pausePomodoro(true);
        UI.toast('Pomodoro complete — take a break.');
        Store.setQuiet('_ui.pomodoroSecs', (Number(state.study?.pomodoroMinutes) || 25) * 60);
        syncPomodoroDisplay();
        return;
      }
      Store.setQuiet('_ui.pomodoroSecs', next);
      syncPomodoroDisplay();
    }, 1000);
    syncPomodoroDisplay();
    document.querySelector('[data-action="pomo-start"]')?.setAttribute('disabled', 'disabled');
    document.querySelector('[data-action="pomo-pause"]')?.removeAttribute('disabled');
  }

  function pausePomodoro(silent) {
    clearInterval(pomoInterval);
    pomoInterval = null;
    Store.setQuiet('_ui.pomodoroRunning', false);
    document.querySelector('[data-action="pomo-start"]')?.removeAttribute('disabled');
    document.querySelector('[data-action="pomo-pause"]')?.setAttribute('disabled', 'disabled');
    if (!silent) syncPomodoroDisplay();
  }

  function resetPomodoro() {
    pausePomodoro(true);
    Store.setQuiet('_ui.pomodoroSecs', (Number(state.study?.pomodoroMinutes) || 25) * 60);
    syncPomodoroDisplay();
  }
})();
